config/routes.rb
Rails.application.routes.draw do
  
  resources :insurance_brokers
  # You can have the root of your site routed with "root"
  root 'welcome#index'
  devise_for :users
  
  resources :makes do
      collection {post :import}
  end
  
  resources :vehicles do
      collection {post :import}
  end
  
  resources :versions do
    collection {post :import}
  end
 
  resources :corredors do
      collection {get ':corredor/:id', to: 'corredors#consulta', as: 'consulta'}
      collection {post  :modelo, :year, :version, :placa, :features, :zona,:poliza,:cedula,:nombre,:sexo,:estado,:fnacimiento,:tfijo,:tcelular, :ibero_sum, :informacion,:email, :add_versionList, :add_actualCoti }
     
  end

  resources :form_uni_seguros do
    get :get_marcas_by_anio,   on: :collection
    get :get_modelo_vehicle,   on: :collection
    get :get_version_automv,   on: :collection
    get :integrador,           on: :collection
  end
  
  resources :integrators do
    post :generic_quotation,   on: :collection
  end
  
  resources :cotiz_apps
end

app/models/insurance_broker.rb
class InsuranceBroker < ActiveRecord::Base
  belongs_to :user
end

app/controllers/insurance_brokers_controller.rb
class InsuranceBrokersController < ApplicationController
  before_action :set_insurance_broker, only: [:show, :edit, :update, :destroy]

  # GET /insurance_brokers
  # GET /insurance_brokers.json
  def index
    @insurance_brokers = InsuranceBroker.all
  end

  # GET /insurance_brokers/1
  # GET /insurance_brokers/1.json
  def show
  end

  # GET /insurance_brokers/new
  def new
    @insurance_broker = InsuranceBroker.new
  end

  # GET /insurance_brokers/1/edit
  def edit
  end

  # POST /insurance_brokers
  # POST /insurance_brokers.json
  def create
    @insurance_broker = InsuranceBroker.new(insurance_broker_params)

    respond_to do |format|
      if @insurance_broker.save
        format.html { redirect_to @insurance_broker, notice: 'Insurance broker was successfully created.' }
        format.json { render :show, status: :created, location: @insurance_broker }
      else
        format.html { render :new }
        format.json { render json: @insurance_broker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /insurance_brokers/1
  # PATCH/PUT /insurance_brokers/1.json
  def update
    respond_to do |format|
      if @insurance_broker.update(insurance_broker_params)
        format.html { redirect_to @insurance_broker, notice: 'Insurance broker was successfully updated.' }
        format.json { render :show, status: :ok, location: @insurance_broker }
      else
        format.html { render :edit }
        format.json { render json: @insurance_broker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /insurance_brokers/1
  # DELETE /insurance_brokers/1.json
  def destroy
    @insurance_broker.destroy
    respond_to do |format|
      format.html { redirect_to insurance_brokers_url, notice: 'Insurance broker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_insurance_broker
      @insurance_broker = InsuranceBroker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def insurance_broker_params
      params.require(:insurance_broker).permit(:users_id, :insurance, :intermediary_code, :plan_code, :plan_review, :discount_rate)
    end
end

app/helpers/insurance_brokers_helper.rb
module InsuranceBrokersHelper
end

app/views/insurance_brokers/_form.html.erb
<%= simple_form_for(@insurance_broker) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :users %>
    <%= f.input :insurance %>
    <%= f.input :intermediary_code %>
    <%= f.input :plan_code %>
    <%= f.input :plan_review %>
    <%= f.input :discount_rate %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/insurance_brokers/edit.html.erb
<h1>Editing Insurance Broker</h1>

<%= render 'form' %>

<%= link_to 'Show', @insurance_broker %> |
<%= link_to 'Back', insurance_brokers_path %>

app/views/insurance_brokers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Insurance Brokers</h1>

<table>
  <thead>
    <tr>
      <th>Users</th>
      <th>Insurance</th>
      <th>Intermediary code</th>
      <th>Plan code</th>
      <th>Plan review</th>
      <th>Discount rate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @insurance_brokers.each do |insurance_broker| %>
      <tr>
        <td><%= insurance_broker.users %></td>
        <td><%= insurance_broker.insurance %></td>
        <td><%= insurance_broker.intermediary_code %></td>
        <td><%= insurance_broker.plan_code %></td>
        <td><%= insurance_broker.plan_review %></td>
        <td><%= insurance_broker.discount_rate %></td>
        <td><%= link_to 'Show', insurance_broker %></td>
        <td><%= link_to 'Edit', edit_insurance_broker_path(insurance_broker) %></td>
        <td><%= link_to 'Destroy', insurance_broker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Insurance broker', new_insurance_broker_path %>

app/views/insurance_brokers/new.html.erb
<h1>New Insurance Broker</h1>

<%= render 'form' %>

<%= link_to 'Back', insurance_brokers_path %>

app/views/insurance_brokers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Users:</strong>
  <%= @insurance_broker.users %>
</p>

<p>
  <strong>Insurance:</strong>
  <%= @insurance_broker.insurance %>
</p>

<p>
  <strong>Intermediary code:</strong>
  <%= @insurance_broker.intermediary_code %>
</p>

<p>
  <strong>Plan code:</strong>
  <%= @insurance_broker.plan_code %>
</p>

<p>
  <strong>Plan review:</strong>
  <%= @insurance_broker.plan_review %>
</p>

<p>
  <strong>Discount rate:</strong>
  <%= @insurance_broker.discount_rate %>
</p>

<%= link_to 'Edit', edit_insurance_broker_path(@insurance_broker) %> |
<%= link_to 'Back', insurance_brokers_path %>