config/routes.rb
Rails.application.routes.draw do
  
  resources :insurance_brokers
  # You can have the root of your site routed with "root"
  root 'welcome#index'
  devise_for :users
  
  resources :makes do
      collection {post :import}
  end
  
  resources :vehicles do
      collection {post :import}
  end
  
  resources :versions do
    collection {post :import}
  end
 
  resources :corredors do
      collection {get ':corredor/:id', to: 'corredors#consulta', as: 'consulta'}
      collection {post  :modelo, :year, :version, :placa, :features, :zona,:poliza,:cedula,:nombre,:sexo,:estado,:fnacimiento,:tfijo,:tcelular, :ibero_sum, :informacion,:email, :add_versionList, :add_actualCoti }
     
  end

  resources :form_uni_seguros do
    get :get_marcas_by_anio,   on: :collection
    get :get_modelo_vehicle,   on: :collection
    get :get_version_automv,   on: :collection
    get :integrador,           on: :collection
  end
  
  resources :integrators do
    post :generic_quotation,   on: :collection
  end
  
  resources :cotiz_apps
end

app/models/cotiz_app.rb
class CotizApp < ActiveRecord::Base
  has_many :insurance_responses
end

app/controllers/cotiz_apps_controller.rb
class CotizAppsController < ApplicationController
  before_action :set_cotiz_app, only: [:show, :edit, :update, :destroy]

  # GET /cotiz_apps
  # GET /cotiz_apps.json
  def index
    @cotiz_apps = CotizApp.all
  end

  # GET /cotiz_apps/1
  # GET /cotiz_apps/1.json
  def show
    @marca   = Make.find_by(:code => @cotiz_app.vehicle_brand).make
    @modelo  = Vehicle.find_by(:make => @cotiz_app.vehicle_brand, :code => @cotiz_app.vehicle_model).model
    @version = Version.find_by(:make => @cotiz_app.vehicle_brand, :model => @cotiz_app.vehicle_model, :code => @cotiz_app.vehicle_version).version
    
    
    @universitas = JSON.parse(InsuranceResponse.where(:cotiz_app_id => @cotiz_app.id, :insurance => "universitas").last.response) rescue []
    @vivir       = JSON.parse(InsuranceResponse.where(:cotiz_app_id => @cotiz_app.id, :insurance => "vivir").last.response) rescue []
    @estar       = JSON.parse(InsuranceResponse.where(:cotiz_app_id => @cotiz_app.id, :insurance => "estar").last.response) rescue []
    @oriental    = JSON.parse(InsuranceResponse.where(:cotiz_app_id => @cotiz_app.id, :insurance => "oriental").last.response) rescue []
    @ibero       = JSON.parse(InsuranceResponse.where(:cotiz_app_id => @cotiz_app.id, :insurance => "ibero").last.response) rescue []

    respond_to do |format|
      format.html
      format.pdf do
        send_data ReportPdf.new(@cotiz_app).render, filename: "cotizacion_#{@cotiz_app.id}.pdf", type: "application/pdf", disposition: "inline"
      end
      format.xlsx { render xlsx: 'show', filename: "show.xlsx"}
      format.json { render json: @cotiz_app }
    end
  end
  
  # GET /cotiz_apps/new
  def new
    @cotiz_app = CotizApp.new
  end

  # GET /cotiz_apps/1/edit
  def edit
  end

  # POST /cotiz_apps
  # POST /cotiz_apps.json
  def create
    @cotiz_app = CotizApp.new(cotiz_app_params)

    respond_to do |format|
      if @cotiz_app.save
        format.html { redirect_to  cotiz_app_path(@cotiz_app), notice: 'Cotiz app was successfully created.' }
        format.json { render :show, status: :created, location: @cotiz_app }
      else
        format.html { render :new }
        format.json { render json: @cotiz_app.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cotiz_apps/1
  # PATCH/PUT /cotiz_apps/1.json
  def update
    respond_to do |format|
      if @cotiz_app.update(cotiz_app_params)
        format.html { redirect_to @cotiz_app, notice: 'Cotiz app was successfully updated.' }
        format.json { render :show, status: :ok, location: @cotiz_app }
      else
        format.html { render :edit }
        format.json { render json: @cotiz_app.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cotiz_apps/1
  # DELETE /cotiz_apps/1.json
  def destroy
    @cotiz_app.destroy
    respond_to do |format|
      format.html { redirect_to cotiz_apps_url, notice: 'Cotiz app was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cotiz_app
      @cotiz_app = CotizApp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cotiz_app_params
      params.require(:cotiz_app).permit(:name, :lastname, :dni_type, :dni_number, :local_code_area, :local_phone, :movil_code_area, :movil_phone, :birthday, :marital_status, :sex, :email, :vehicle_year, :vehicle_brand, :vehicle_model, :vehicle_version, :plaque, :intermediate_code, :state, :plan_code, :plan_review, :discount_rate, :vehicle_use, :kilometer_zero, :vehicle_type)
    end
end

app/helpers/cotiz_apps_helper.rb
module CotizAppsHelper
end

app/views/cotiz_apps/_form.html.erb
<%= simple_form_for(@cotiz_app, :html=> { class: "form-horizontal" }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    
    <div class="form-group">
      <%= f.label :name, nil, :class => "control-label col-sm-3 required_custom" %>
      <div class="col-md-7">
       <%= f.input :name,label: false, placeholder: "Nombre", autofocus: true, input_html: { class: "form-control", value: "Javier" }%>    
      </div>
    </div>
    <div class="form-group">
      <%= f.label :lastname, nil, :class => "control-label col-sm-3 required_custom" %>
      <div class="col-md-7">
       <%= f.input :lastname,label: false, placeholder: "Apellido", autofocus: true, input_html: { class: "form-control", value: "Urbano" }%>    
      </div>
    </div>
    <div class="form-group">
      <%= f.label :dni_type, nil, :class => "control-label col-sm-3 required_custom" %>
      <div class="col-md-7">
       <%= f.input :dni_type,label: false, as: :select, collection: options_for_nacionalidad, :prompt => "Seleccione...", :selected => (@cotiz_app.dni_type.present? ? @cotiz_app.dni_type : "V"), autofocus: true, input_html: { class: "form-control" }%>    
      </div>
    </div>
    <div class="form-group">
      <%= f.label :dni_number, nil, :class => "control-label col-sm-3 required_custom" %>
      <div class="col-md-7">
       <%= f.input :dni_number,label: false, placeholder: "Cédula", autofocus: true, input_html: { class: "form-control", value: "18621606" }%>    
      </div>
    </div>
    <div class="form-group">
      <%= f.label :local_code_area, nil, :class => "control-label col-sm-3 required_custom" %>
      <div class="col-md-7">
       <%= f.input :local_code_area,label: false, placeholder: "Código Área Tlf. Local", autofocus: true, input_html: { class: "form-control", value: "212" }%>    
      </div>
    </div>
    <div class="form-group">
      <%= f.label :local_phone, nil, :class => "control-label col-sm-3 required_custom" %>
      <div class="col-md-7">
       <%= f.input :local_phone,label: false, placeholder: "Tlf. Local", autofocus: true, input_html: { class: "form-control", value: "2513436" }%>    
      </div>
    </div>
    <div class="form-group">
      <%= f.label :movil_code_area, nil, :class => "control-label col-sm-3 required_custom" %>
      <div class="col-md-7">
       <%= f.input :movil_code_area,label: false, placeholder: "Código Área Tlf. Móvil", autofocus: true, input_html: { class: "form-control", value: "416" }%>    
      </div>
    </div>
    <div class="form-group">
      <%= f.label :movil_phone, nil, :class => "control-label col-sm-3 required_custom" %>
      <div class="col-md-7">
       <%= f.input :movil_phone,label: false,  placeholder: "Tlf. Móvil", autofocus: true, input_html: { class: "form-control", value: "5833809" }%>    
      </div>
    </div>
    <div class="form-group">
      <%= f.label :birthday, nil, :class => "control-label col-sm-3 required_custom" %>
      <div class="col-md-7">
       <%= f.input :birthday,label: false, as: :string, placeholder: "F/Nacimiento", autofocus: true, input_html: { class: "form-control", value: "12-03-1988" }%>    
      </div>
    </div>
    <div class="form-group">
      <%= f.label :marital_status, nil, :class => "control-label col-sm-3 required_custom" %>
      <div class="col-md-7">
       <%= f.input :marital_status,label: false, as: :select, collection: options_for_marital_state, :prompt => "Seleccione...", :selected => (@cotiz_app.marital_status.present? ? @cotiz_app.marital_status : "C") , autofocus: true, input_html: { class: "form-control" }%>    
      </div>
    </div>
    <div class="form-group">
      <%= f.label :sex, nil, :class => "control-label col-sm-3 required_custom" %>
      <div class="col-md-7">
       <%= f.input :sex,label: false, as: :select, collection: options_for_sex, :prompt => "Seleccione...", :selected => (@cotiz_app.sex.present? ? @cotiz_app.sex : "M"), autofocus: true, input_html: { class: "form-control" }%>    
      </div>
    </div>
    <div class="form-group">
      <%= f.label :email, nil, :class => "control-label col-sm-3 required_custom" %>
      <div class="col-md-7">
       <%= f.input :email,label: false, placeholder: "Email", autofocus: true, input_html: { class: "form-control", value: "javierurbano11@gmail.com" }%>    
      </div>
    </div>
    <div class="form-group">
      <%= f.label :vehicle_year, nil, :class => "control-label col-sm-3 required_custom" %>
      <div class="col-md-7">
       <%= f.input :vehicle_year,label: false, as: :select, collection: options_for_vehicle_year, :prompt => "Seleccione...", autofocus: true, input_html: { class: "form-control" }%>    
      </div>
    </div>
    <div class="form-group">
      <%= f.label :vehicle_brand, nil, :class => "control-label col-sm-3 required_custom" %>
      <div class="col-md-7">
       <%= f.input :vehicle_brand,label: false, as: :select, collection: [], :prompt => "Seleccione...", autofocus: true, input_html: { class: "form-control" }%>    
      </div>
    </div>
    <div class="form-group">
      <%= f.label :vehicle_model, nil, :class => "control-label col-sm-3 required_custom" %>
      <div class="col-md-7">
       <%= f.input :vehicle_model,label: false, as: :select, collection: [], :prompt => "Seleccione...", autofocus: true, input_html: { class: "form-control" }%>    
      </div>
    </div>
    <div class="form-group">
      <%= f.label :vehicle_version, nil, :class => "control-label col-sm-3 required_custom" %>
      <div class="col-md-7">
       <%= f.input :vehicle_version,label: false, as: :select, collection: [], :prompt => "Seleccione...", autofocus: true, input_html: { class: "form-control" }%>    
      </div>
    </div>
    <div class="form-group">
      <%= f.label :plaque, nil, :class => "control-label col-sm-3 required_custom" %>
      <div class="col-md-7">
       <%= f.input :plaque,label: false, placeholder: "Placa Vehiculo", autofocus: true, input_html: { class: "form-control", value: "ABDOKD" }%>    
      </div>
    </div>
    <div class="form-group">
      <%= f.label :intermediate_code, nil, :class => "control-label col-sm-3 required_custom" %>
      <div class="col-md-7">
       <%= f.input :intermediate_code,label: false, placeholder: "Código Intermediario", autofocus: true, input_html: { class: "form-control", value: "026206" }%>    
      </div>
    </div>
    <div class="form-group">
      <%= f.label :state, nil, :class => "control-label col-sm-3 required_custom" %>
      <div class="col-md-7">
       <%= f.input :state,label: false, as: :select, collection: ESTADOS, :prompt => "Seleccione...", autofocus: true, input_html: { class: "form-control" }%>    
      </div>
    </div>
    <div class="form-group">
      <%= f.label :plan_code, nil, :class => "control-label col-sm-3 required_custom" %>
      <div class="col-md-7">
       <%= f.input :plan_code,label: false, placeholder: "Código Plan", autofocus: true, input_html: { class: "form-control", value: "102" }%>    
      </div>
    </div>
    <div class="form-group">
      <%= f.label :plan_review, nil, :class => "control-label col-sm-3 required_custom" %>
      <div class="col-md-7">
       <%= f.input :plan_review,label: false, placeholder: "Revisión", autofocus: true, input_html: { class: "form-control", value: "001" }%>    
      </div>
    </div>
    <div class="form-group">
      <%= f.label :discount_rate, nil, :class => "control-label col-sm-3 required_custom" %>
      <div class="col-md-7">
       <%= f.input :discount_rate,label: false, placeholder: "Tasa descuento", autofocus: true, input_html: { class: "form-control", value: "5" }%>    
      </div>
    </div>
    <div class="form-group">
      <%= f.label :vehicle_use, nil, :class => "control-label col-sm-3 required_custom" %>
      <div class="col-md-7">
       <%= f.input :vehicle_use,label: false, as: :select, collection: USO_VEHICULO, :selected => "01", autofocus: true, input_html: { class: "form-control" }%>    
      </div>
    </div>
    <div class="form-group">
      <%= f.label :kilometer_zero, nil, :class => "control-label col-sm-3 required_custom" %>
      <div class="col-md-7">
       <%= f.input :kilometer_zero,label: false, as: :select, collection: ["S","N"], :selected => "N", autofocus: true, input_html: { class: "form-control" }%>    
      </div>
    </div>
    <div class="form-group">
      <%= f.label :vehicle_type, nil, :class => "control-label col-sm-3 required_custom" %>
      <div class="col-md-7">
       <%= f.input :vehicle_type,label: false, as: :select, collection: TIPO_VEHICULO, :selected => "001", autofocus: true, input_html: { class: "form-control" }%>    
      </div>
    </div>
  </div>
  
  <div class="form-group">
    <div class="col-md-10">
      <%= f.button :submit, :class => "btn btn-primary pull-right" %>
      <%= link_to 'Back', cotiz_apps_path, :class => "btn btn-default pull-right" %>
    </div>
  </div>
<% end %>
<script type="text/javascript">
  
  $(document).ready(function(){
    $("#cotiz_app_vehicle_year").change(function(){
        var selected = $(this).val();
        $.ajax({
            type: "GET",
            data: { anio: selected },
            url: "/form_uni_seguros/get_marcas_by_anio",
            success: function(response){
              $("#cotiz_app_vehicle_brand").html(function(){
                var options_str = "<option value=''>Seleccione...</option>";

                $.map(response, function(v){
                  options_str += "<option value='" + v.codmarca +"'>" + v.descmarca + "</option>";
                }).join('');
                return options_str;
              });
            }
        });
    });
    
    $("#cotiz_app_vehicle_brand").change(function(){
        var anio_veh = $("#cotiz_app_vehicle_year").val();
        var selected = $(this).val();
        $.ajax({
            type: "GET",
            data: { anio: anio_veh, marca: selected },
            url: "/form_uni_seguros/get_modelo_vehicle",
            success: function(response){
              $("#cotiz_app_vehicle_model").html(function(){
                var options_str = "<option value=''>Seleccione...</option>";

                $.map(response, function(v){
                  options_str += "<option value='" + v.codmodelo +"'>" + v.descmodelo + "</option>";
                }).join('');
                return options_str;
              });
            }
        });
    });
    
    $("#cotiz_app_vehicle_model").change(function(){
        var anio_veh = $("#cotiz_app_vehicle_year").val();
        var mark_veh = $("#cotiz_app_vehicle_brand").val();
        var selected = $(this).val();
        $.ajax({
            type: "GET",
            data: { anio: anio_veh, marca: mark_veh, modelo: selected },
            url: "/form_uni_seguros/get_version_automv",
            success: function(response){
              $("#cotiz_app_vehicle_version").html(function(){
                var options_str = "<option value=''>Seleccione...</option>";

                $.map(response, function(v){
                  options_str += "<option value='" + v.codversion +"'>" + v.descversion + "</option>";
                }).join('');
                return options_str;
              });
            }
        });
    });
  });
</script>

app/views/cotiz_apps/edit.html.erb
<h1>Editing Cotiz App</h1>

<%= render 'form' %>

<%= link_to 'Show', @cotiz_app %> |
<%= link_to 'Back', cotiz_apps_path %>

app/views/cotiz_apps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cotiz Apps</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Lastname</th>
      <th>DNI</th>
      <!--
      <th>Birthday</th>
      <th>Marital status</th>
      -->
      <th>Sex</th>
      <th>Email</th>
      <th>Vehicle year</th>
      <th>Vehicle brand</th>
      <th>Vehicle model</th>
      <th>Vehicle version</th>
      <th>Intermediate code</th>
      <th>State</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @cotiz_apps.each do |cotiz_app| %>
      <tr>
        <td><%= cotiz_app.name %></td>
        <td><%= cotiz_app.lastname %></td>
        <td><%= "#{cotiz_app.dni_type}-#{cotiz_app.dni_number}" %> </td>
        <!--<td><%# cotiz_app.birthday %></td>-->
        <!--<td><%# cotiz_app.marital_status %></td>-->
        <td><%= cotiz_app.sex %></td>
        <td><%= cotiz_app.email %></td>
        <td><%= cotiz_app.vehicle_year %></td>
        <td><%= cotiz_app.vehicle_brand %></td>
        <td><%= cotiz_app.vehicle_model %></td>
        <td><%= cotiz_app.vehicle_version %></td>
        <td><%= cotiz_app.intermediate_code %></td>
        <td><%= cotiz_app.state %></td>
        <td><%= link_to 'Show', cotiz_app %> |</td>
        <td><%= link_to 'Pdf',  cotiz_app_path(cotiz_app, :format => "pdf") %> |</td>
        <td><%= link_to 'Xls',  cotiz_app_path(cotiz_app, :format => "xlsx") %> |</td>
        <td><%= link_to 'Edit', edit_cotiz_app_path(cotiz_app) %> |</td>
        <td><%= link_to 'Destroy', cotiz_app, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cotiz app', new_cotiz_app_path %>

app/views/cotiz_apps/index.xlsx.erb
<%=
Axlsx::Package.new do |p|
      p.workbook.add_worksheet(:name => "Pie Chart") do |sheet|
        sheet.add_row ["Simple Pie Chart"]
        %w(first second third).each { |label| sheet.add_row [label, rand(24)+1] }
        sheet.add_chart(Axlsx::Pie3DChart, :start_at => [0,5], :end_at => [10, 20], :title => "example 3: Pie Chart") do |chart|
          chart.add_series :data => sheet["B2:B4"], :labels => sheet["A2:A4"],  :colors => ['FF0000', '00FF00', '0000FF']
        end
      end
      p.serialize('simple.xlsx')
end
%>

app/views/cotiz_apps/new.html.erb
<h1>New Cotiz App</h1>

<%= render 'form' %>

app/views/cotiz_apps/show.html.erb
<!--<p id="notice"><%# notice %></p>-->

<p>
  <strong>Nombre y Apellido:</strong>
  <%= "#{@cotiz_app.name} #{@cotiz_app.lastname}" %>
</p>

<p>
  <strong>DNI:</strong>
  <%= "#{@cotiz_app.dni_type} #{@cotiz_app.dni_number}" %>
</p>

<p>
  <strong>Tlf. Fijo:</strong>
  <%= "#{@cotiz_app.local_code_area}-#{@cotiz_app.local_phone}" %>
</p>

<p>
  <strong>Tlf. Móvil:</strong>
  <%= "#{@cotiz_app.movil_code_area}-#{@cotiz_app.movil_phone}" %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @cotiz_app.birthday %>
</p>

<p>
  <strong>Marital status:</strong>
  <%= @cotiz_app.marital_status %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @cotiz_app.sex %>
</p>

<p>
  <strong>Email:</strong>
  <%= @cotiz_app.email %>
</p>

<p>
  <strong>Vehicle year:</strong>
  <%= @cotiz_app.vehicle_year %>
</p>

<p>
  <strong>Vehicle brand:</strong>
  <%= @cotiz_app.vehicle_brand %>
</p>

<p>
  <strong>Vehicle model:</strong>
  <%= @cotiz_app.vehicle_model %>
</p>

<p>
  <strong>Vehicle version:</strong>
  <%= @cotiz_app.vehicle_version %>
</p>

<p>
  <strong>Vehicle plaque:</strong>
  <%= @cotiz_app.plaque %>
</p>

<p>
  <strong>Intermediate code:</strong>
  <%= @cotiz_app.intermediate_code %>
</p>

<p>
  <strong>State:</strong>
  <%= @cotiz_app.state %>
</p>

<p>
  <strong>Plan code:</strong>
  <%= @cotiz_app.plan_code %>
</p>

<p>
  <strong>Plan review:</strong>
  <%= @cotiz_app.plan_review %>
</p>

<p>
  <strong>Discount rate:</strong>
  <%= @cotiz_app.discount_rate %>
</p>

<p>
  <strong>Vehicle use:</strong>
  <%= @cotiz_app.vehicle_use %>
</p>

<p>
  <strong>Kilometer zero:</strong>
  <%= @cotiz_app.kilometer_zero %>
</p>

<p>
  <strong>Vehicle type:</strong>
  <%= @cotiz_app.vehicle_type %>
</p>

<%= link_to "Cotizar", 'javascript:;',  :onclick=>"cotiza();", :remote => false, :class => "btn btn-success", :title => "Cotizar" %>
<%= link_to 'Edit', edit_cotiz_app_path(@cotiz_app) %> |
<%= link_to 'Back', cotiz_apps_path %>

<div class="form-group">
  <div class="col-md-1"></div>
  <div class="col-md-10">
    <div id="resulset_universitas"></div>
  </div>
  <div class="col-md-1"></div>
</div>
<div class="form-group">
  <div class="col-md-1"></div>
  <div class="col-md-10">
    <div id="resulset_vivir"></div>
  </div>
  <div class="col-md-1"></div>
</div>
<div class="form-group">
  <div class="col-md-1"></div>
  <div class="col-md-10">
    <div id="resulset_oriental"></div>
  </div>
  <div class="col-md-1"></div>
</div>

<script type="text/javascript">
  
  
    
   function cotiza() {
    
    parametros = {
      object_id: <%= @cotiz_app.id %>,
      name: "<%= @cotiz_app.name %>",
      lastname: "<%= @cotiz_app.lastname %>",
      dni_type: "<%= @cotiz_app.dni_type %>", 
      dni_number: "<%= @cotiz_app.dni_number %>",
      local_code_area: "<%= @cotiz_app.local_code_area %>",
      local_phone: "<%= @cotiz_app.local_phone %>",
      movil_code_area: "<%= @cotiz_app.movil_code_area %>",
      movil_phone: "<%= @cotiz_app.movil_phone %>",
      birthday: "<%= Date.parse(@cotiz_app.birthday.to_s).strftime("%d-%m-%Y") %>",
      marital_status: "<%= @cotiz_app.marital_status %>",
      sex: "<%= @cotiz_app.sex %>",
      email: "<%= @cotiz_app.email %>",
      vehicle_year: "<%= @cotiz_app.vehicle_year %>",
      vehicle_brand: "<%= @cotiz_app.vehicle_brand %>",
      vehicle_model: "<%= @cotiz_app.vehicle_model %>",
      vehicle_version: "<%= @cotiz_app.vehicle_version %>",
      plaque: "<%= @cotiz_app.plaque %>",
      intermediate_code: "<%= @cotiz_app.intermediate_code %>",
      state: "<%= @cotiz_app.state %>",
      plan_code: "<%= @cotiz_app.plan_code %>",
      plan_review: "<%= @cotiz_app.plan_review %>",
      discount_rate: "<%= @cotiz_app.discount_rate %>",
      vehicle_use: "<%= @cotiz_app.vehicle_use %>",
      kilometer_zero: "<%= @cotiz_app.kilometer_zero %>",
      vehicle_type: "<%= @cotiz_app.vehicle_type %>"
    };
    
    cotiza_universitas(parametros);
    cotiza_vivir(parametros);
    cotiza_oriental(parametros);
  };
  
  function cotiza_universitas(params){
    $.ajax({
            type: "POST",
            data: $.extend({aseguradora: "universitas"}, params),
            url: "/integrators/generic_quotation",
            success: function(response){
              var str_show = "";
              str_show += "<h2>Seguros Universitas:</h2>";
              str_show += "<b>Nro. Cotización: </b> " + response[0].numcotizacion + "<br>";
              $.each(response[0].pcursor[0], function(i, item){
                str_show += "<b>Descripción: </b> " + item.descripcion + "<br>";
                str_show += "<b>Prima: </b> "       + item.mtoprima    + "<br>";
                str_show += "<b>Suma Aseg: </b> "   + item.mtosumaaseg + "<br>";
                str_show += "<b>Tasa: </b> "        + item.mtotasa     + "<br>";
                str_show += "<br><br>";
              });
              $("#resulset_universitas").html(str_show);
            }
    });
  };
  
  function cotiza_vivir(params){
    $.ajax({
            type: "POST",
            data: $.extend({aseguradora: "vivir"}, params),
            url: "/integrators/generic_quotation",
            success: function(response){
              console.log(response);
              var str_show = "";
              str_show += "<h2>Vivir Seguros</h2>";
              str_show += "<b>Nro. Cotización: </b> " + response[0].numero + "<br>";
              str_show += "<a href='"+response[0].archivo+"'>Descargar</a><br>";
              $.each(response[0].cotizacion, function(i, item){
                str_show += "<b>Cobertura: </b> " + item.cobertura + "<br>";
                str_show += "<b>Prima: </b> "     + item.prima     + "<br>";
                str_show += "<b>Suma: </b> "      + item.suma      + "<br>";
                str_show += "<b>Tasa: </b> "      + item.tasa      + "<br>";
                str_show += "<br><br>";
              });
              $("#resulset_vivir").html(str_show);
            }
    });
  };
  
  function cotiza_oriental(params){
    $.ajax({
            type: "POST",
            data: $.extend({aseguradora: "oriental"}, params),
            url: "/integrators/generic_quotation",
            success: function(response){
              console.log(response);
              
              var str_show = "";
              str_show += "<h2>Oriental de Seguros:</h2>";
              str_show += "<b>Nro. Cotización: </b> " + response[0].plan[0].nrocoti + "<br>";
              
              $.each(response[0].plan, function(i, item){
                str_show += "<b>Tipo: </b> " + item.tipo + "<br>";
                str_show += "<b>Prima Total: </b> "       + item.primatotal    + "<br>";
                str_show += "<h4>Coberturas:</h4>";
                $.each(item.coberturas, function(j, element){
                  str_show += "<b>Cobertura: </b> "   + element.nombre + "<br>";
                  str_show += "<b>Suma Aseg: </b> "   + element.suma   + "<br>";
                  str_show += "<b>Tasa: </b> "        + element.tasa   + "<br>";
                  str_show += "<b>Prima: </b> "       + element.prima  + "<br>";
                  str_show += "<br>";
                });
                
                str_show += "<br><br>";
              });
              
              $("#resulset_oriental").html(str_show);
              
            }
    });
  };
  
</script>