config/routes.rb
Rails.application.routes.draw do
  
  resources :insurance_brokers
  # You can have the root of your site routed with "root"
  root 'welcome#index'
  devise_for :users
  
  resources :makes do
      collection {post :import}
  end
  
  resources :vehicles do
      collection {post :import}
  end
  
  resources :versions do
    collection {post :import}
  end
 
  resources :corredors do
      collection {get ':corredor/:id', to: 'corredors#consulta', as: 'consulta'}
      collection {post  :modelo, :year, :version, :placa, :features, :zona,:poliza,:cedula,:nombre,:sexo,:estado,:fnacimiento,:tfijo,:tcelular, :ibero_sum, :informacion,:email, :add_versionList, :add_actualCoti }
     
  end

  resources :form_uni_seguros do
    get :get_marcas_by_anio,   on: :collection
    get :get_modelo_vehicle,   on: :collection
    get :get_version_automv,   on: :collection
    get :integrador,           on: :collection
  end
  
  resources :integrators do
    post :generic_quotation,   on: :collection
  end
  
  resources :cotiz_apps
end

app/models/corredor.rb
class Corredor < ActiveRecord::Base

	before_save do
		self.ced = "#{nacion}#{cedula}"
		self.fnacimiento = "#{dia}/#{mes}/#{anio}"
		self.telefono = "#{cod1}-#{tfijo}"
		self.celular = "#{cod2}-#{tcelular}"
	end

	has_many :insurance_responses
end

app/controllers/corredors_controller.rb
class CorredorsController < ApplicationController
  before_action :set_corredor, only: [:show, :edit, :update, :destroy]

  # GET /corredors
  # GET /corredors.json
  def index
    @corredors = Corredor.all
  end

  # POST /corredors
  # POST /corredors.json
  def modelo
    @corredor = Corredor.find_by_id(params[:id])
    @corredor.update(corredor_params)
    render :action=>'year', :id=>'@corredor.id', notice: 'Modelo was successfully created.'

  end

  def year
    @corredor = Corredor.find_by_id(params[:id])
    @corredor.update(corredor_params)
    render :action=>'version', :id=>'@corredor.id', notice: "Year Added Successfully"
  end

  def version
    @corredor = Corredor.find_by_id(params[:id])
    @corredor.update(corredor_params)
    render :action=>'placa', :id=>'@corredor.id', notice: "Version Added Successfully"
  end

  def placa
    @corredor = Corredor.find_by_id(params[:id])
    @corredor.update(corredor_params)
    render :action=>'features', :id=>'@corredor.id', notice: "Placa Added Successfully"
  end

  def features
    @corredor = Corredor.find_by_id(params[:id])
    @corredor.update(corredor_params)
    render :action=>'zona', :id=>'@corredor.id', notice: "Features Added Successfully"
  end

  def zona
    @corredor = Corredor.find_by_id(params[:id])
    @corredor.update(corredor_params)
    render :action=>'cedula', :id=>'@corredor.id', notice: "Zona Added Successfully"
  end

  def poliza
    @corredor = Corredor.find_by_id(params[:id])
    @corredor.update(corredor_params)
    render :action=>'cedula', :id=>'@corredor.id', notice: "Poliza Added Successfully"
  end

  def cedula
    @corredor = Corredor.find_by_id(params[:id])
    @corredor.update(corredor_params)
    render :action=>'nombre', :id=>'@corredor.id', notice: "Cedula Added Successfully"
  end

  def nombre
    @corredor = Corredor.find_by_id(params[:id])
    @corredor.update(corredor_params)
    render :action=>'sexo', :id=>'@corredor.id', notice: "Nombre Added Successfully"
  end


  def sexo
    @corredor = Corredor.find_by_id(params[:id])
    if @corredor.nil?
      render :action=>'show'
    else
      @corredor.update(corredor_params)
      render :action=>'email', :id=>'@corredor.id', notice: "Sexo Added Successfully"
    end
  end

  def email
    @corredor = Corredor.find_by_id(params[:id])
    @corredor.update(corredor_params)
    render :action=>'estado', :id=>'@corredor.id', notice: "Correo Added Successfully"
  end

  def estado
    @corredor = Corredor.find_by_id(params[:id])
    @corredor.update(corredor_params)
    render :action=>'fnacimiento', :id=>'@corredor.id', notice: "Estado Added Successfully"
  end

  def fnacimiento
    @corredor = Corredor.find_by_id(params[:id])
    @corredor.update(corredor_params)
    render :action=>'tfijo', :id=>'@corredor.id', notice: "Fecha de Nacimiento Added Successfully"
  end

  def tfijo
    @corredor = Corredor.find_by_id(params[:id])
    @corredor.update(corredor_params)
    render :action=>'tcelular', :id=>'@corredor.id', notice: "Telefono fijo Added Successfully"
  end

  def tcelular
    @corredor = Corredor.find_by_id(params[:id])
    @corredor.update(corredor_params)
    render :action=>'show', :id=>'@corredor.id', notice: "informacion Added Successfully"
  end

  def ibero_sum
    @corredor = Corredor.find_by_id(params[:id])
    @corredor.update(corredor_params)
    render :action=>'show', :id=>'@corredor.id', notice: "Added Successfully"
  end

   def informacion
    @corredor = Corredor.find_by_id(params[:id])
    @corredor.update(corredor_params)
    redirect_to corredor_path(@corredor), notice: "informacion Added Successfully"
  end



  def consulta
    @corredor = Corredor.find_by_id(params[:id])

    @universitas = Report.where(:corredor_id => @corredor.id, :insurance => "universitas").last
    if(@universitas.blank?)
        @universitas = Report.new
        @universitas.status = 0
    end
    @vivir = Report.where(:corredor_id => @corredor.id, :insurance => "vivir").last
    if(@vivir.blank?)
        @vivir = Report.new
        @vivir.status = 0
    end
    @oriental = Report.where(:corredor_id => @corredor.id, :insurance => "oriental").last
    if(@oriental.blank?)
        @oriental = Report.new
        @oriental.status = 0
    end
    @ibero = Report.where(:corredor_id => @corredor.id, :insurance => "ibero").last
    if(@ibero.blank?)
        @ibero = Report.new
        @ibero.status = 0
    end
    @estar = Report.where(:corredor_id => @corredor.id, :insurance => "estar").last
    if(@estar.blank?)
        @estar = Report.new
        @estar.status = 0
    end
    dob = Date.strptime( @corredor.fnacimiento, '%d/%m/%Y' )
    now = Time.now.utc.to_date
    @age = now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)

  end

  def add_versionList
    
    @corredor = Corredor.find_by_id(params[:id])
    @oriental = Report.where(:corredor_id => @corredor.id, :insurance => "oriental").last
    if(@oriental.blank?)
        @oriental = Report.new
        @oriental.status = 0
    end

    version_list = params[:user]
    @oriental.versionList = version_list
    @oriental.save   
    render :nothing => true
  end

  def add_actualCoti
    
    @corredor = Corredor.find_by_id(params[:id])
    @oriental = Report.where(:corredor_id => @corredor.id, :insurance => "oriental").last
    if(@oriental.blank?)
        @oriental = Report.new
        @oriental.status = 0
    end


    actualCoti = params[:user]
    @oriental.actualCoti = actualCoti
    @oriental.save   
    render :nothing => true
  end

  # GET /corredors/1
  # GET /corredors/1.json
  def show
    puts params
    respond_to do |format|
      format.html
      format.pdf do
        send_data ReportPdf.new(@corredor).render, filename: "cotizacion_#{@corredor.id}.pdf", type: "application/pdf", disposition: "inline"
      end
      format.xlsx { render xlsx: 'show', filename: "cotizacion_#{@corredor.id}.xlsx"}
      format.json { render json: @cotiz_app }
    end

  end

  # GET /corredors/new
  def new
    @corredor = Corredor.new
  end

  # GET /corredors/1/edit
  def edit
    @corredor = Corredor.find(params[:id])
    make = @corredor.marca
    @aux = Vehicle.where(make: make)
  end

  # POST /corredors
  # POST /corredors.json
  def create
    @corredor = Corredor.new(corredor_params)

    respond_to do |format|
      if @corredor.save
        format.html { render :action=>'modelo', :id=>'@corredor.id', notice: 'Corredor was successfully created.' }
        format.json { render :modelo, status: :created, location: @corredor_modelo}
      else
        format.html { render :new }
        format.json { render json: @corredor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /corredors/1
  # PATCH/PUT /corredors/1.json
  def update
    respond_to do |format|
      if @corredor.update(corredor_params)
        format.html { redirect_to @corredor, notice: 'Corredor was successfully updated.' }
        format.json { render :show, status: :ok, location: @corredor }
      else
        format.html { render :edit }
        format.json { render json: @corredor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /corredors/1
  # DELETE /corredors/1.json
  def destroy
    @corredor.destroy
    respond_to do |format|
      format.html { redirect_to corredors_url, notice: 'Corredor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_corredor

      # Se verifica que se esta accediendo correctamente.
      @test = Corredor.where(id: params[:id]).first
      if (@test.nil?)
        render :action=>"index"
      else
        @corredor = Corredor.find(params[:id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def corredor_params
      params.require(:corredor).permit(:marca, :modelo, :year, :version, :placa, :zona, :poliza, :nombre, :apellido, :sexo, :estado, :fnacimiento, :informacion, :dia, :mes, :anio, :cedula, :nacion,:tfijo, :cod1, :tcelular, :cod2, :ced, :telefono, :celular,:email, :vehicle_type, :vehicle_use, :cerokm, :sumaAsegurada, :versionList, :user, :actualCoti)
    end

end

app/helpers/corredors_helper.rb
module CorredorsHelper
end

app/views/corredors/cedula.html.erb
<div class="container fluid" id="viewtitle">
  <div class="vistas">
    <h1><img src="<%= image_url 'logojohan.jpg' %>" alt="bienvenido"></h1>
    <h3 class="subtitle"><img src="<%= image_url 'carnet.png' %>" alt="carrito">  Cedula del Asegurado</h2>
  </div>
</div>

<%= form_for @corredor, :url => cedula_corredors_path, :method => :post  do |f| %>
  <% if @corredor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@corredor.errors.count, "error") %> prohibited this corredor from being saved:</h2>

      <ul>
      <% @corredor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= hidden_field_tag :id, @corredor.id %>
<div class="container-fluid" id="user_data">
    <div class="col-sm-12">
      <div class="thumbnail">
        <div class="row">
          <div class="col-sm-6" id="separator">
            <img src="<%= image_url 'horizontal-badge.png' %>" alt="identificacion.jpg">
          </div>
          <div class="col-sm-6" >
            <div class="inputs">
              <select name="corredor[nacion]">
                <option>V</option>
                <option>E</option>
              </select>
              <input id="corredor_cedula" name="corredor[cedula]" type="text" class="k-textbox" pattern="\d{7,8}"       placeholder="Ejemplo: 06123456" required validationMessage="Deben ser 8 dígitos" autofocus/>
            <p><%= f.submit 'Siguiente', class: "btn btn-primary" %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/corredors/edit.html.erb
<h1>Editing Corredor</h1>

<%= render 'form' %>

<%= link_to 'Show', @corredor %> |
<%= link_to 'Back', corredors_path %>

app/views/corredors/features.html.erb
<!-- Definicion de las variables a utilizar. -->
<script type="text/javascript">
  var usoV = "";   // Valor actual del dropdown correspondiente a uso vehiculo.
  var tipoV = "";  // Valor actual del dropdown correspondiente a tipo vehiculo.
  var ceroKm = ""; // Valor actual del dropdown correspondiente a cero kilometro.
</script>

<div class="container fluid" id="viewtitle">
  <div class="vistas">
    <h1><img src="<%= image_url 'logojohan.jpg' %>" alt="bienvenido"></h1>
    <h3 class="subtitle"><img src="<%= image_url 'car.png' %>" alt="carrito">  Características del Vehículo</h2>
  </div>
</div>

<%= form_for @corredor, :url => features_corredors_path, :method => :post  do |f| %>
  <% if @corredor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@corredor.errors.count, "error") %> prohibited this corredor from being saved:</h2>

      <ul>
      <% @corredor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= hidden_field_tag :id, @corredor.id %>
<div class="container-fluid" id="user_data">
    <div class="col-sm-12">
      <div class="thumbnail">
        <div class="row">
          <div class="col-sm-6" id="separator">
            <img src="<%= image_url 'plaque.png' %>" alt="placa.jpg">
          </div>
          <div class="col-sm-6" >
            <div id = "separador">
              <h4> Tipo del Vehiculo </h4>
              <select name="corredor[vehicle_type]" id="tipoVehiculo">
                  <option value="" selected disabled >Seleccione..</option>
                  <option value="particular">Particular</option>
                  <option value="rustico">Rustico</option>
              </select>


              <br><br><h4> Uso de Vehiculo </h4>
               <select name="corredor[vehicle_use]" id="usoVehiculo">
                  <option value="" selected disabled >Seleccione..</option>
                  <option value="particular" >Particular</option>
                  <option value="taxi">Taxi</option>   
                  <option value="transporte">Transporte</option>

                </select>
                
                <br><br><h4> ¿Es cero kilometro? </h4>
                <select name="corredor[cerokm]" id="cerokm">
                  <option value = "" selected disabled >Seleccione..</option>
                  <option value = "S">Si</option>
                  <option value = "N">No</option>
                </select>

                <script type="text/javascript">

                  function option(){

                      usoV = $( "#usoVehiculo option:selected" ).val();
                      tipoV = $( "#tipoVehiculo option:selected" ).val();
                      cerokm = $("#cerokm option:selected").val();
              
                   
                      console.log("vehiculos: " + usoV + "  tipo: " + tipoV + " cero: " + cerokm);

                      if (usoV != "" && tipoV != "" && cerokm != ""){
                        $("#btnSiguiente").css("display", "inline")
                      }
                  }

                </script>
                <br>
                <br>
                <br>
                <div id = "btnSiguiente" style="display:none;">
                  <p><%= f.submit 'Siguiente', class: "btn btn-primary", id: 'btnsep' %></p>
                </div>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

<script type="text/javascript">
    $('select[id=usoVehiculo]').on('change', option);
    $('select[id=tipoVehiculo]').on('change', option);
    $('select[id=cerokm]').on('change', option);
</script>

app/views/corredors/index.html.erb
<p id="notice"><%= notice %></p>

<div class="pageoptions container">
  <div class="option pull-left"><%= button_to "Inicio", root_path, :method => "get", class: "btn btn-primary"%></div> 
  <div class="option pull-right"><%= button_to 'Nueva Cotizacion',new_corredor_path, :method => "get", class: "btn btn-primary"%></div> 
</div>

   

<h1 id="prueba" style="text-align:center">Cotizaciones</h1>

<table  cellpadding="15" class="table table-striped table-bordered">
  <thead>
    <tr>
      <th style="text-align:center">Nombre</th>
      <th style="text-align:center">Apellido</th>
      <th style="text-align:center">Marca</th>
      <th style="text-align:center">Modelo</th>
      <th style="text-align:center">Año</th>
      <th style="text-align:center">Version</th>
      <th style="text-align:center">Fecha Cotizacion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% if @corredors == nil %>
      <% @corredors = Corredor.all %>
    <% end %>
    
    
    <% @corredors.order(updated_at: :desc).each do |corredor| %>
      <tr>

        <!-- Se verifica que el ultimo valor que se solicita es proporcionado. -->  
        <% if corredor.tcelular != nil %>
          <%@marca   = Make.find_by(:code => corredor.marca).make %>
          <%@modelo  = Vehicle.find_by(:make => corredor.marca, :code => corredor.modelo).model %>
          <% @version = Version.find_by(:make => corredor.marca, :model => corredor.modelo, :code => corredor.version) %>

          <% if @version != nil %>
            <td style="text-align:center"><%="#{corredor.nombre}".capitalize %></td>
            <td style="text-align:center"><%="#{corredor.apellido}".capitalize %></td>
            <td style="text-align:center"><%= @marca %></td>
            <td style="text-align:center"><%= @modelo%></td>
            <td style="text-align:center"><%= corredor.year %></td>
            <td style="text-align:center"><%= @version.version %></td>
            <td style="text-align:center"><%= corredor.created_at %></td>
            <td>
              <%= link_to 'Ver', consulta_corredors_path(corredor, :id=>corredor.id) %>|
              <%= link_to 'Destroy', corredor, method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/corredors/informacion.html.erb
<h1>Introduzca Informacion</h1>

<%= form_for @corredor, :url => informacion_corredors_path, :method => :post  do |f| %>
  <% if @corredor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@corredor.errors.count, "error") %> prohibited this corredor from being saved:</h2>

      <ul>
      <% @corredor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :informacion %><br>
    <select name="corredor[informacion]">
		<option >Propetario</option>
		<option >Conductor Habitual</option>
		<option >Ninguno</option>
	</select>
  </div>
 
  <div class="actions">
    <%= hidden_field_tag :id, @corredor.id %>
    <%= f.submit %>
  </div>
<% end %>

app/views/corredors/modelo.html.erb
<div class="container fluid" id="viewtitle">
  <div class="vistas">
    <h1 id="responsive-header"><img src="<%= image_url 'logojohan.jpg' %>" alt="bienvenido"></h1>
    <h3 class="subtitle"><img src="<%= image_url 'car.png' %>" alt="carrito">  Modelo</h2>
  </div>
</div>

<%= form_for @corredor, :url => modelo_corredors_path, :method => :post  do |f| %>
  <% if @corredor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@corredor.errors.count, "error") %> prohibited this corredor from being saved:</h2>

      <ul>
      <% @corredor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="container" id="lista_modelos">
  <ul class="list-group">
      <% lista = Vehicle.where(make: @corredor.marca) %>
      <% lista.order('model').each do |modelo| %>
    <li class="list-group-item">
      <%= hidden_field_tag :id, @corredor.id %>
      <%= f.radio_button :modelo, modelo[:code], :onclick => "this.form.submit()"%> 
      <%= modelo.model %>
    </li>
      <% end %>
  </ul>
</div>

<% end %>
<%# link_to 'Back', corredors_path %>

app/views/corredors/new.html.erb
<div class="container fluid" id="viewtitle">
		<h1>Nueva Cotizacion</h1>
		<h3 class="subtitle"><img src="<%= image_url 'car.png'%>" alt="carrito">Marca del Vehículo</h3>
</div>

<%= form_for(@corredor)  do |f| %>
  <% if @corredor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@corredor.errors.count, "error") %> prohibited this corredor from being saved:</h2>

      <ul>
      <% @corredor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
   <% end %>


  <div  class="container" id="busqueda_alterna">

    <div class="col-md-6" class="ba_mensaje">
      <h4>¿No la encuentras? Buscala dentro de la Lista ...</h4>
    </div>

    <div class="col-md-6" class="ba_select">
     
      <h4 name="corredor[marca]"><%= f.collection_select :marca, ::Make.all, :code,:make, {prompt: "Seleccione..."},html_options= {:class => 'radio',:onchange => "this.form.submit()" }%><h4>
    </div>
      <%= hidden_field_tag :id, @corredor.id%>
<!--  :disabled => x == y  -->
  </div>

<div class="container" id="vistamarcas">
  <div class="row">
    <div class="col-sm-2 col-xs-6">
      <fieldset class="corredor[marca]">
        <div class="img_marca">
          <input type="radio" name="corredor[marca]" class="radio_marca" value="006" id="Audi" onClick = "this.form.submit()">
          <label for="Audi"><%=image_tag("1.jpg", alt: "Audi") %></label>
        </div>
      </fieldset>
    </div> 
    
    <div class="col-sm-2 col-xs-6">
      <fieldset class="corredor[marca]">
        <div class="img_marca">
          <input type="radio" name="corredor[marca]" class="radio_marca" value="013" id="Chevrolet" onClick = "this.form.submit()">
          <label for="Chevrolet"><%=image_tag("5.jpg", alt: "Chevrolet") %></label>
        </div>
      </fieldset>
    </div>

    <div class="col-sm-2 col-xs-6">
      <fieldset class="corredor[marca]">
        <div class="img_marca">
          <input type="radio" name="corredor[marca]" class="radio_marca" value="038" id="Jeep" onClick = "this.form.submit()">
          <label for="Jeep"><%=image_tag("17.jpg", alt: "Jeep") %></label>
        </div>
      </fieldset>
    </div>

    <div class="col-sm-2 col-xs-6">
      <fieldset class="corredor[marca]">
        <div class="img_marca">
          <input type="radio" name="corredor[marca]" class="radio_marca" value="020" id="Dodge" onClick = "this.form.submit()">
          <label for="Dodge"><%=image_tag("7.jpg", alt: "Dodge") %></label>
        </div>
      </fieldset>
    </div>

    <div class="col-sm-2 col-xs-6">
      <fieldset class="corredor[marca]">
        <div class="img_marca">
          <input type="radio" name="corredor[marca]" class="radio_marca" value="025" id="Fiat" onClick = "this.form.submit()">
          <label for="Fiat"><%=image_tag("41.jpg", alt: "Fiat") %></label>
        </div>
      </fieldset>
    </div>

    <div class="col-sm-2 col-xs-6">
      <fieldset class="corredor[marca]">
        <div class="img_marca">
          <input type="radio" name="corredor[marca]" class="radio_marca" value="026" id="Ford" onClick = "this.form.submit()">
          <label for="Ford"><%=image_tag("9.jpg", alt: "Ford") %></label>
        </div>
      </fieldset>
    </div>
  </div>

  <div class="row">
      <div class="col-sm-2 col-xs-6">
        <fieldset class="corredor[marca]">
          <div class="img_marca">
            <input type="radio" name="corredor[marca]" class="radio_marca" value="014" id="Chrysler" onClick = "this.form.submit()">
            <label for="Chrysler"><%=image_tag("chrysler.png", alt: "Chrysler") %></label>
          </div>
        </fieldset>
      </div>

      <div class="col-sm-2 col-xs-6">
        <fieldset class="corredor[marca]">
          <div class="img_marca">
            <input type="radio" name="corredor[marca]" class="radio_marca" value="074" id="Toyota" onClick = "this.form.submit()">
            <label for="Toyota"><%=image_tag("29.jpg", alt: "Toyota") %></label>
          </div>
        </fieldset>
      </div>

      <div class="col-sm-2 col-xs-6">
        <fieldset class="corredor[marca]">
          <div class="img_marca">
            <input type="radio" name="corredor[marca]" class="radio_marca" value="078" id="Volkswagen" onClick = "this.form.submit()">
            <label for="Volkswagen"><%=image_tag("30.jpg", alt: "Volkswagen") %></label>
          </div>
        </fieldset>
      </div>

      <div class="col-sm-2 col-xs-6">
        <fieldset class="corredor[marca]">
          <div class="img_marca">
            <input type="radio" name="corredor[marca]" class="radio_marca" value="065" id="Renault" onClick = "this.form.submit()">
            <label for="Renault"><%=image_tag("54.jpg", alt: "Renault") %></label>
          </div>
        </fieldset>
      </div>

      <div class="col-sm-2 col-xs-6">
        <fieldset class="corredor[marca]">
          <div class="img_marca">
            <input type="radio" name="corredor[marca]" class="radio_marca" value="189" id="Chery" onClick = "this.form.submit()">
            <label for="Chery"><%=image_tag("4.jpg", alt: "Chery") %></label>
          </div>
        </fieldset>
      </div>

      <div class="col-sm-2 col-xs-6">
        <fieldset class="corredor[marca]">
          <div class="img_marca">
            <input type="radio" name="corredor[marca]" class="radio_marca" value="055" id="Mitsubishi" onClick = "this.form.submit()">
            <label for="Mitsubishi"><%=image_tag("24.jpg", alt: "Mitsubishi") %></label>
          </div>
        </fieldset>
      </div>
    </div>
  </div>
<% end %>

<script>
  $(".radio").select2();
</script>

app/views/corredors/placa.html.erb
<div class="container fluid" id="viewtitle">
  <div class="vistas">
    <h1><img src="<%= image_url 'logojohan.jpg' %>" alt="bienvenido"></h1>
    <h3 class="subtitle"><img src="<%= image_url 'car.png' %>" alt="carrito">  Placa del Vehículo</h2>
  </div>
</div>

<%= form_for @corredor, :url => placa_corredors_path, :method => :post  do |f| %>
  <% if @corredor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@corredor.errors.count, "error") %> prohibited this corredor from being saved:</h2>

      <ul>
      <% @corredor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= hidden_field_tag :id, @corredor.id %>
<div class="container-fluid" id="user_data">
    <div class="col-sm-12">
      <div class="thumbnail">
        <div class="row">
          <div class="col-sm-6" id="separator">
            <img src="<%= image_url 'plaque.png' %>" alt="placa.jpg">
          </div>
          <div class="col-sm-6" >
            <div class="inputs">
              <input id="corredor_placa" name="corredor[placa]" type="text" class="k-textbox" pattern="\w{6,7}"       placeholder="Ejemplo: AOD636" required validationMessage="Deben ser 6 dígitos" autofocus onblur="checkTextField(this);"/>
            <p><%= f.submit 'Siguiente', class: "btn btn-primary" %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/corredors/ver_cotiz.html.erb
<div class="container-fluid" id="viewtitle">
    <h1><img src="<%= image_url 'logojohan.jpg' %>" alt="bienvenido"></h1>
    <h2><img src="<%= image_url 'chart.png' %>" alt="estadisiticas">  Cotizacion Final</h2>
</div>

<%= link_to 'New Corredor', new_corredor_path, :class => "btn btn-primary" %>

<% @quotes = quotes %>
<% @universitas = JSON.parse(InsuranceResponse.where(:cotiz_app_id => @quotes.id, :insurance => "universitas").last.response) %>
<% @oriental    = JSON.parse(InsuranceResponse.where(:cotiz_app_id => @quotes.id, :insurance => "oriental").last.response) %>


 <% @universitas["numcotizacion"] %>