config/routes.rb
Rails.application.routes.draw do
  
  resources :insurance_brokers
  # You can have the root of your site routed with "root"
  root 'welcome#index'
  devise_for :users
  
  resources :makes do
      collection {post :import}
  end
  
  resources :vehicles do
      collection {post :import}
  end
  
  resources :versions do
    collection {post :import}
  end
 
  resources :corredors do
      collection {get ':corredor/:id', to: 'corredors#consulta', as: 'consulta'}
      collection {post  :modelo, :year, :version, :placa, :features, :zona,:poliza,:cedula,:nombre,:sexo,:estado,:fnacimiento,:tfijo,:tcelular, :ibero_sum, :informacion,:email, :add_versionList, :add_actualCoti }
     
  end

  resources :form_uni_seguros do
    get :get_marcas_by_anio,   on: :collection
    get :get_modelo_vehicle,   on: :collection
    get :get_version_automv,   on: :collection
    get :integrador,           on: :collection
  end
  
  resources :integrators do
    post :generic_quotation,   on: :collection
  end
  
  resources :cotiz_apps
end

app/models/corredor.rb
class Corredor < ActiveRecord::Base

	before_save do
		self.ced = "#{nacion}#{cedula}"
		self.fnacimiento = "#{dia}/#{mes}/#{anio}"
		self.telefono = "#{cod1}-#{tfijo}"
		self.celular = "#{cod2}-#{tcelular}"
	end

	has_many :insurance_responses
end

app/models/cotiz_app.rb
class CotizApp < ActiveRecord::Base
  has_many :insurance_responses
end

app/models/form_uni_seguro.rb
class FormUniSeguro < ActiveRecord::Base
end

app/models/insurance_broker.rb
class InsuranceBroker < ActiveRecord::Base
  belongs_to :user
end

app/models/insurance_response.rb
%#
  t.string  :insurance
  t.integer :cotiz_app_id, references :cotiz_app
  t.text    :response
#
class InsuranceResponse < ActiveRecord::Base
  belongs_to :cotiz_app
  belongs_to :corredor
end

app/models/make.rb
class Make < ActiveRecord::Base
  
  #has_many :vehicles, foreign_key: "make", dependent: :destroy
  
	def self.import(file)
		Make.delete_all
		CSV.foreach(file.path, :headers =>true, :encoding => 'ISO-8859-1') do |row|
			Make.create!(row.to_hash)
		end
	end
end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :corredor
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :insurance_brokers
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  
  #belongs_to :make, foreign_key: "code"
  
	def self.import(file)
		Vehicle.delete_all
		CSV.foreach(file.path, :headers =>true, :encoding => 'ISO-8859-1') do |row|
			Vehicle.create!(row.to_hash)
		end
	end
end

app/models/version.rb
class Version < ActiveRecord::Base
  def self.import(file)
		Version.delete_all
		CSV.foreach(file.path, :headers =>true, :encoding => 'ISO-8859-1', :col_sep => ";") do |row|
			Version.create!(row.to_hash)
		end
	end
end

app/controllers/makes_controller.rb
class MakesController < ApplicationController
  before_action :set_make, only: [:show, :edit, :update, :destroy]

  # GET /makes
  # GET /makes.json
  def index
    @makes = Make.all
  end

  # GET /makes/1
  # GET /makes/1.json
  def show
  end

  # GET /makes/new
  def new
    @make = Make.new
  end

  # GET /makes/1/edit
  def edit
  end

  # POST /makes
  # POST /makes.json
  def create
    @make = Make.new(make_params)

    respond_to do |format|
      if @make.save
        format.html { redirect_to @make, notice: 'Make was successfully created.' }
        format.json { render :show, status: :created, location: @make }
      else
        format.html { render :new }
        format.json { render json: @make.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /makes/1
  # PATCH/PUT /makes/1.json
  def update
    respond_to do |format|
      if @make.update(make_params)
        format.html { redirect_to @make, notice: 'Make was successfully updated.' }
        format.json { render :show, status: :ok, location: @make }
      else
        format.html { render :edit }
        format.json { render json: @make.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /makes/1
  # DELETE /makes/1.json
  def destroy
    @make.destroy
    respond_to do |format|
      format.html { redirect_to makes_url, notice: 'Make was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

   def import
      Make.import(params[:file])
      redirect_to makes_path, notice: "Makes Added Successfully"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_make
      @make = Make.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def make_params
      params.require(:make).permit(:make)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/corredors_helper.rb
module CorredorsHelper
end

app/helpers/cotiz_apps_helper.rb
module CotizAppsHelper
end

app/helpers/integrators_helper.rb
module IntegratorsHelper
end

app/helpers/makes_helper.rb
module MakesHelper
  def options_for_vehicles_makes
    Make.all.map { |make| [make.make, make.code] }
  end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
  def options_for_vehicles_models(make)
    Vehicle.where(:make => make).map { |model| [model.model, model.code] } if make.present?
  end
end

app/helpers/versions_helper.rb
module VersionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" style="padding-bottom: 25px;">
      <div class="col-md-1"></div>
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}", :class => "col-md-10" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_user_options.erb
<% if user_signed_in? %>
	<nav id="useroptions">
	  <ul class="nav nav-justified">
  			<li><p>Bienvenido <strong><%= current_user.email %></strong></p></li>
                        <!--
  			<li><%# link_to 'Formulario de Prueba',  form_uni_seguros_path, :class => 'btn btn-xs btn-link' %></li>
  			<li><%# link_to 'Formulario de Prueba II',  integrators_path, :class => 'btn btn-xs btn-link' %></li>
  			<li><%# link_to 'Formulario de Prueba III', cotiz_apps_path, :class => 'btn btn-xs btn-link' %></li>
                        -->
  			<li><%= link_to 'Perfil', edit_user_registration_path, :class => 'btn btn-xs btn-link' %></li>
  			<li><%= link_to "Salir", destroy_user_session_path, method: :delete, :class => 'btn btn-xs btn-link'  %></li>
      </ul>
    </nav>  
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CorredorLeal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Lato&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Ek+Mukta:800' rel='stylesheet' type='text/css'>
  <link href="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/css/select2.min.css" rel="stylesheet" />
  <script src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/js/select2.min.js"></script>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <!-- Bootstrap -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
  <!--<link href="css/bootstrap.min.css" rel="stylesheet">-->
</head>
<body>
  
<div class="page-wrap">
  <%= render 'layouts/user_options' %>
  <%= render 'layouts/messages' %>  
  <%=yield%>    
</div>

<footer class="site-footer">
  <img src="<%= image_url 'skepsis.png' %>" alt="skepsis logo">
  <h4>Powered by Skepsis Consulting, C.A.</h4>
</footer>

</body>
</html>